<?php 

/**
 * @file
 * myblock.module
 * This will build a custom block that will contain
 * WYSIWYG markup and an uploaded picture file.
 * This custom block will be built within a module 
 * called custom_block.
 */


function myblock_block_info() {
	$blocks = array();
	$blocks['my_block'] = array(
		'info' => t('My Custom Block'),
	);

	return $blocks;
}

/**
 * Implements hook_block_configure().
 */

function myblock_block_configure($delta='') {
	$form = array();

	switch($delta) {
		case 'my_block' :
		// text field form element
		$form['text_body'] = array (
			'#type' => 'text_format',
			'#title' => t('Enter your text here in WYSIWIG format'),
			'#default_value' => variable_get('text_variable', ''),
		);

		// File selection form element
		$form['file'] = array(
			'#name' => 'block_image',
			'#type' => 'managed_file',
			'#title' => t('Choose an Image File'),
			'#description' => variable_get('block_image_fid', ''),
			'#upload_location' => 'public://block_image/',
			'#upload validators' => array(
				'file_validate_extensions' => array('gif png jpg jpeg')
			),
		);
		break;
	}
	return $form;
}

/**
 * Implements hook_block_save();
 **/

function myblock_block_save($delta = '', $edit = array()) {
	switch($delta) {
		case 'my_block' :
		//saving the WYSIWIG text
		variable_set('text_variable', $edit['text_body']['value']);

		//saving the file, setting it to a permanent state, setting a FID state
		$file = file_load($edit['file']);
		$file->status = FILE_STATUS_PERMANENT;
		file_save($file);
		$block = block_load('custom_block', $delta);
		file_usage_add($file, 'custom_block', 'block', $block->bid);
		variable_set('block_image_fid', $file->fid);
		break;
	}

}






